### PR TITLE
assets: fix btn allignment and design issues

### LINKED ISSUE #1013: #3506 interactive event
**URL:** Interactive event Modules like https://aplus-dev.liqd.net/teststadt/interactiveevents/interactive-event-3/
**important screensize:** *Both*
**device & browser:** Safari *Version 14.0 (15610.1.28.1.9, 15610)*
**Comment/Question:**

Sorry, I think I tested too early cause I didn't see some of these new things and I can't find my old issue anymore to add these things, so I just created this new one instead.
 
[m-201208-interactive-event-questions.pdf](https://github.com/liqd/adhocracy-plus/files/5659526/m-201208-interactive-event-questions.pdf)
[d-201208-interactive-event-questions.pdf](https://github.com/liqd/adhocracy-plus/files/5659523/d-201208-interactive-event-questions.pdf)

### PR DESCRIPTION
**Pull request by phillimorland**
partial fix for #749
fixes #1013

### CODE REVIEW

File: adhocracy-plus/assets/js/app.js [hunk 1]
```diff
@@ -53,6 +54,10 @@ function init () {
     slidesToShow: 1,
     slidesToScroll: 1
   })
+
+  if ($.fn.select2) {
+    $('.js-select2').select2()
+  }
 }
```
Comment (phillimorland) [inline adhocracy-plus/assets/js/app.js:61]: I'm leaving this in until we know which we'll use but I'm not calling it on the select in this pull request

Comment (rmader) [reply adhocracy-plus/assets/js/app.js:61]: :+1:

File: apps/projects/templates/a4_candy_projects/project_detail.html [hunk 2]
```diff
@@ -21,6 +21,17 @@
 {% endif %}
 {% endblock %}
 
+<!-- ensure cookie overlay for embedded videos -->
+{% block extra_css %}
+  {{ block.super }}
+    <link rel="stylesheet" href="{% static 'dsgvo_video_embed.css' %}" />
```
Comment (rmader) [inline apps/projects/templates/a4_candy_projects/project_detail.html:27]: Can you remove it from `livequestion_module_detail.html` again then? Otherwise we load it twice.

**Review by rmader — APPROVED** [review]
One nit, otherwise from a quick test here looks good!

File: apps/projects/templates/a4_candy_projects/project_detail.html (hunk 2 above)
Comment (phillimorland) [reply apps/projects/templates/a4_candy_projects/project_detail.html:27]: oh good point, done.

Comment (rmader) [reply apps/projects/templates/a4_candy_projects/project_detail.html:27]: Thanks!
